version: '3.7'

services:

  data-collector-postgres:
    image: $DC_IMAGE
    ports:
      - 9990:9990
      - 9992:9992
    volumes:
    - $WORKDIR/profile/$PROFILE/conf:/conf
    - $WORKDIR/certs:/certs
    #- /Volumes/SSB BusinessSSL/certs:/certs
    depends_on:
    - dc-postgres-db

  dc-postgres-db:
    image: postgres:12-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - dc-postgres-test:/var/lib/postgresql/data
    - $WORKDIR/profile/$PROFILE/init-db-and-user.sql:/docker-entrypoint-initdb.d/init.sql

  dc-adminer:
    image: adminer
    ports:
    - 8980:8080
    depends_on:
    - dc-postgres-db

  grafana:
    image: grafana/grafana:6.6.2
    ports:
    - 3000:3000
    depends_on:
    - prom

  prom:
    image: prom/prometheus:v2.16.0
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
    - 9090:9090
    depends_on:
    - data-collector-postgres

volumes:
  dc-postgres-test:
