version: '3.7'

services:

  data-collector:
    image: data-collector:dev
    ports:
    - 9090:9090
    volumes:
    - ./conf:/conf
    - ./certs:/certs
    - /tmp/rawdata:/rawdata
    depends_on:
      - dc-postgres-db

  dc-postgres-db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - dc-postgres-test:/var/lib/postgresql/data
    - ./init-db-and-user.sql:/docker-entrypoint-initdb.d/init.sql

  dc-adminer:
    image: adminer
    ports:
    - 8080:8080
    depends_on:
      - dc-postgres-db

volumes:
  dc-postgres-test:
