version: '3.7'

services:

  data-collector-postgres:
    image: $DC_IMAGE
    ports:
      - 9990:9990
    volumes:
    - $WORKDIR/profile/$PROFILE/conf:/conf
    - $WORKDIR/certs:/certs
    depends_on:
      - dc-postgres-db

  dc-postgres-db:
    image: postgres:12-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - dc-postgres-test:/var/lib/postgresql/data
    - $WORKDIR/profile/$PROFILE/init-db-and-user.sql:/docker-entrypoint-initdb.d/init.sql

  dc-adminer:
    image: adminer
    ports:
      - 8980:8080
    depends_on:
      - dc-postgres-db

volumes:
  dc-postgres-test:
