version: '3.7'

services:

  dataCollector:
    image: data-collector:dev
    ports:
    - 9090:9090
    volumes:
    - ./conf:/conf
    - ./certs:/certs
    - /tmp/rawdata:/rawdata
    depends_on:
      - dcPostgresDb

  dcPostgresDb:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - dc-postgres-test:/var/lib/postgresql/data
    - ./init-db-and-user.sql:/docker-entrypoint-initdb.d/init.sql

  dcAdminer:
    image: adminer
    ports:
    - 8080:8080
    depends_on:
      - dcPostgresDb

volumes:
  dc-postgres-test:

