version: '3.7'

services:

  data-collector-gcs:
    image: $DC_IMAGE
    ports:
      - 9990:9990
      - 9992:9992
    volumes:
      - $WORKDIR/profile/$PROFILE/conf:/conf
      - $WORKDIR/target:/target
